swagger: '2.0'

info:
  version: "1.0"
  title: BakeryRateApp

paths:
  /getAllBakeryItems:
    get:
      description: |
        Get all `Bakery` objects in array.
      responses:
        200:
          description: Bakery query run successfully
          schema:
            title: arrayOfBakery
            type: array
            items:
              title: bakery
              $ref: '#/definitions/Bakery'
        404:
          description: No bakery found
        500:
          description: Internal server error
  /getBakeryItemsByRating/{bakeryRating}:
    get:
      description: |
        Gets `Bakery` objects by rating number.
      parameters:
        - name: bakeryRating
          in: path
          description: The minimum rating
          required: true
          type: number
      responses:
        200:
          description: Bakery query run successfully
          schema:
              title: bakery
              $ref: '#/definitions/Bakery'
        404:
          description: Not found items with higher rating than the parameter
        500:
          description: Internal server error
  /createBakery:
    post:
      description: |
        Create a `Bakery` objects.
      parameters:
        - name: bakery
          in: body
          description: Bakery to save
          required: true
          schema:
            title: Bakery
            $ref: '#/definitions/Bakery'
      responses:
        200:
          description: Bakery created successfully
          schema:
            title: bakeryId
            type: integer
        500:
          description: Internal server error
  /updateBakery:
    post:
      description: |
        Update a `Bakery` objects.
      parameters:
        - name: bakery
          in: body
          description: Bakery to update
          required: true
          schema:
            title: bakery
            $ref: '#/definitions/Bakery'
      responses:
        200:
          description: Bakery updated succesfully
          schema:
            title: bakeryId
            type: integer
        404:
          description: Bakery not found
        500:
          description: Internal server error
  /deleteBakery/{bakeryId}:
    post:
      description: |
        Delete a `Bakery` objects.
      parameters:
        - name: bakeryId
          in: path
          description: Bakery to delete
          required: true
          type: integer
      responses:
        200:
          description: Bakery deleted successfully
        404:
          description: Bakery not found
        500:
          description: Internal server error
  /logInUser:
    post:
      description: |
        Authenticate user by user name and password.
      parameters:
        - name: user
          in: body
          description: User to authenticate
          required: true
          schema:
            description: User object
            $ref: '#/definitions/User'
      responses:
        200:
          description: User successfully logged in
        401:
          description: User authentication failed
        404:
          description: User not found
        500:
          description: Internal server error
  /createUser:
    post:
      description: |
       Create a `User` object.
      parameters:
        - name: user
          in: body
          description: User to create
          required: true
          schema:
            description: User object
            $ref: '#/definitions/User'
      responses:
        200:
          description: User successfully created
        500:
          description: Internal server error
definitions:
  Bakery:
    properties:
      Id:
        type: integer
      name:
        type: string
      details:
        type: string
      bakeryType:
        type: string
      address:
        type: string
      rate:
        type: number
      price:
        type: integer
      picture:
        type: string
  User:
    properties:
      userName:
        type: string
      password:
        type: string